#!/bin/bash
# YCSB_SOSD on

set -e
set -o pipefail


##
# *** WORKLOAD CONFIGURATION ***
recordcount=$((600*1000*1000))  # 100 M
recordcount2=$((200*1000*1000))  # 100 M
operationcount=$((10*1000*1000))  # 10 M
field_len=64
field_cnt=1  # value: 10*100 =~ 1 KB

##
# build
cd ../build
cmake --build . -- -j
cd -
ycsb=../build/ycsb

num_bg=8
retraining_threshold=21

for num_threads in 32; do

	for req_dist in sosd_fb sosd_wiki; do
		rm -rf /mnt-koo/db/*
		sync; echo 1 | sudo tee /proc/sys/vm/drop_caches
		$ycsb \
			--recordcount=${recordcount2} \
	    --operationcount=${operationcount} \
		  --fieldlength=${field_len} \
			--fieldcount=${field_cnt} \
			--threads=${num_threads} \
		  --workloads="l" \
		  --max_background_jobs=$(( num_bg + 1 )) \
			--distribution=${req_dist} \
			--merged_model_error_bound=${retraining_threshold}

		for wl in c x y; do
			sync; echo 1 | sudo tee /proc/sys/vm/drop_caches
			$ycsb \
				--recordcount=${recordcount2} \
		    --operationcount=${operationcount} \
			  --fieldlength=${field_len} \
				--fieldcount=${field_cnt} \
				--threads=${num_threads} \
			  --workloads=${wl} \
				--max_background_jobs=$(( num_bg + 1 )) \
				--distribution=${req_dist} \
				--merged_model_error_bound=${retraining_threshold}
		done
	done

	for req_dist in sosd_osm sosd_books; do
		rm -rf /mnt-koo/db/*
		sync; echo 1 | sudo tee /proc/sys/vm/drop_caches
		$ycsb \
			--recordcount=${recordcount} \
	    --operationcount=${operationcount} \
		  --fieldlength=${field_len} \
			--fieldcount=${field_cnt} \
			--threads=${num_threads} \
		  --workloads="l" \
		  --max_background_jobs=$(( num_bg + 1 )) \
			--distribution=${req_dist} \
			--merged_model_error_bound=${retraining_threshold}

		for wl in c x y; do
			sync; echo 1 | sudo tee /proc/sys/vm/drop_caches
			$ycsb \
				--recordcount=${recordcount} \
		    --operationcount=${operationcount} \
			  --fieldlength=${field_len} \
				--fieldcount=${field_cnt} \
				--threads=${num_threads} \
			  --workloads=${wl} \
				--max_background_jobs=$(( num_bg + 1 )) \
				--distribution=${req_dist} \
				--merged_model_error_bound=${retraining_threshold}
		done
	done


done
