#!/bin/bash

set -e
set -o pipefail


##
# *** WORKLOAD CONFIGURATION ***
recordcount=$((50*1000*1000))  # 100 M
operationcount=$((10*1000*1000))  # 10 M
scan_operationcount=$((10*1000*1000))  # 10 M
field_len=64
field_cnt=1  # value: 10*100 =~ 1 KB
req_dist="uniform"

##
# build
cd ../build
cmake --build . -- -j
cd -
ycsb=../build/ycsb

num_threads=32
num_bg=8
learned_error_bound=8
merged_error_bound=21
db_path="/mnt-koo/db"


rm -rf ${db_path}/*

sync; echo 1 | sudo tee /proc/sys/vm/drop_caches
$ycsb \
	--recordcount=${recordcount} \
	--operationcount=${operationcount} \
	--fieldlength=${field_len} \
	--fieldcount=${field_cnt} \
	--threads=${num_threads} \
	--workloads="l" \
	--max_background_jobs=$(( num_bg + 1 )) \
	--distribution=${req_dist} \
	--learned_model_error_bound=${learned_error_bound} \
	--merged_model_error_bound=${merged_error_bound} \
	--db_path=${db_path}

for wl in a c; do
	sync; echo 1 | sudo tee /proc/sys/vm/drop_caches
	$ycsb \
		--recordcount=${recordcount} \
		--operationcount=${operationcount} \
		--fieldlength=${field_len} \
		--fieldcount=${field_cnt} \
		--threads=${num_threads} \
		--workloads=${wl} \
		--max_background_jobs=$(( num_bg + 1 )) \
		--distribution=${req_dist} \
		--learned_model_error_bound=${learned_error_bound} \
		--merged_model_error_bound=${merged_error_bound} \
		--db_path=${db_path}
done

