#!/bin/bash

set -e
set -o pipefail


##
# *** WORKLOAD CONFIGURATION ***
recordcount=$((100*1000*1000))  # 100 M
operationcount=$((10*1000*1000))  # 10 M
scan_operationcount=$((10*1000*1000))  # 10 M
field_len=100
field_cnt=10  # value: 10*100 =~ 1 KB
#num_threads=10

##
# build
cd ../build
/usr/bin/cmake --build . -- -j
cd -
ycsb=../build/ycsb

#for req_dist in "uniform"; do
req_dist="uniform"
#for num_threads in 1 4 8 16; do
for num_threads in 20; do
  # following this order: https://github.com/brianfrankcooper/YCSB/wiki/Core-Workloads#running-the-workloads
  rm -rf /mnt-koo/*  # clear db
  $ycsb \
    --recordcount=${recordcount} \
    --operationcount=${operationcount} \
    --fieldlength=${field_len} \
    --fieldcount=${field_cnt} \
    --threads=${num_threads} \
    --workloads="l,c" \
    --distribution=${req_dist} > /koo/tests/hyperbourbon/05.30/lc_100G_10M_t${num_threads}.txt
done
