#!/bin/bash

set -e
set -o pipefail


##
# *** WORKLOAD CONFIGURATION ***
recordcount=$((50*1000*1000))  # 100 M
operationcount=$((10*1000*1000))  # 10 M
scan_operationcount=$((10*1000*1000))  # 10 M
field_len=64
field_cnt=1  # value: 10*100 =~ 1 KB
req_dist="uniform"

##
# build
cd ../build
cmake --build . -- -j
cd -
ycsb=../build/ycsb

num_bg=8
num_l=1
learned_error_bound=8

for num_threads in 32; do

	rm -rf /mnt-koo/db/*
	sync; echo 1 | sudo tee /proc/sys/vm/drop_caches
	$ycsb \
	--recordcount=${recordcount} \
	--operationcount=${operationcount} \
	--fieldlength=${field_len} \
	--fieldcount=${field_cnt} \
	--threads=${num_threads} \
	--workloads="l" \
	--max_background_jobs=$(( num_bg + 1 )) \
	--max_learning_jobs=${num_l} \
	--distribution=${req_dist} \
	--learned_model_error_bound=${learned_error_bound}

	for wl in a c; do
		sync; echo 1 | sudo tee /proc/sys/vm/drop_caches
		$ycsb \
		--recordcount=${recordcount} \
		--operationcount=${operationcount} \
		--fieldlength=${field_len} \
		--fieldcount=${field_cnt} \
		--threads=${num_threads} \
		--workloads=${wl} \
		--max_background_jobs=$(( num_bg + 1 )) \
		--max_learning_jobs=${num_l} \
		--distribution=${req_dist} \
		--learned_model_error_bound=${learned_error_bound}
	done

done
