#!/bin/bash

set -e
set -o pipefail


##
# *** WORKLOAD CONFIGURATION ***
recordcount=$((600*1000*1000))  # 100 M
recordcount2=$((200*1000*1000))  # 100 M
operationcount=$((10*1000*1000))  # 10 M
field_len=64
field_cnt=1  # value: 10*100 =~ 1 KB

##
# build
cd ../build
cmake --build . -- -j
cd -
ycsb=../build/ycsb

num_threads=32
num_bg=8
num_l=4
learned_error_bound=8
mod=0			# 0: HyperBourbon(CBA), 1: HyperBourbon(Always), 2: HyperWiscKey
db_path="/mnt-koo/db"

sosd_data_dir="/koo/SOSD/data"
sosd_lookups_dir="/koo/SOSD/data/lookups"



for req_dist in wiki_ts_200M fb_200M; do

	rm -rf ${db_path}/*

	sync; echo 1 | sudo tee /proc/sys/vm/drop_caches
	$ycsb \
		--recordcount=${recordcount2} \
		--operationcount=${operationcount} \
		--fieldlength=${field_len} \
		--fieldcount=${field_cnt} \
		--threads=${num_threads} \
		--workloads="l" \
		--distribution="sosd" \
		--max_background_jobs=$(( num_bg + 1 )) \
		--max_learning_jobs=${num_l} \
		--learned_model_error_bound=${learned_error_bound} \
		--mod=${mod} \
		--db_path=${db_path} \
		--sosd_data_path="${sosd_data_dir}/${req_dist}_uint64"

	for wl in c x y; do
		sync; echo 1 | sudo tee /proc/sys/vm/drop_caches
		$ycsb \
			--recordcount=${recordcount2} \
			--operationcount=${operationcount} \
			--fieldlength=${field_len} \
			--fieldcount=${field_cnt} \
			--threads=${num_threads} \
			--workloads=${wl} \
			--distribution="sosd" \
			--max_background_jobs=$(( num_bg + 1 )) \
			--max_learning_jobs=${num_l} \
			--learned_model_error_bound=${learned_error_bound} \
			--mod=${mod} \
			--db_path=${db_path} \
			--sosd_lookups_path="${sosd_lookups_dir}/${req_dist}_uint64_equality_lookups_10M"
	done
done


for req_dist in books_600M osm_cellids_600M normal_600M lognormal_600M; do

	rm -rf ${db_path}/*

	sync; echo 1 | sudo tee /proc/sys/vm/drop_caches
	$ycsb \
		--recordcount=${recordcount} \
		--operationcount=${operationcount} \
		--fieldlength=${field_len} \
		--fieldcount=${field_cnt} \
		--threads=${num_threads} \
		--workloads="l" \
		--distribution="sosd" \
		--max_background_jobs=$(( num_bg + 1 )) \
		--max_learning_jobs=${num_l} \
		--learned_model_error_bound=${learned_error_bound} \
		--mod=${mod} \
		--db_path=${db_path} \
		--sosd_data_path="${sosd_data_dir}/${req_dist}_uint64"

	for wl in c x y; do
		sync; echo 1 | sudo tee /proc/sys/vm/drop_caches
		$ycsb \
			--recordcount=${recordcount} \
			--operationcount=${operationcount} \
			--fieldlength=${field_len} \
			--fieldcount=${field_cnt} \
			--threads=${num_threads} \
			--workloads=${wl} \
			--distribution="sosd" \
			--max_background_jobs=$(( num_bg + 1 )) \
			--max_learning_jobs=${num_l} \
			--learned_model_error_bound=${learned_error_bound} \
			--mod=${mod} \
			--db_path=${db_path} \
			--sosd_lookups_path="${sosd_lookups_dir}/${req_dist}_uint64_equality_lookups_10M"
	done
done
